name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fjuza1/autoPortfolio

      - name: Install dependencies
        run: npm install
        working-directory: fjuza1/autoPortfolio

      - name: Start server
        run: npm start
        working-directory: fjuza1/autoPortfolio

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:1234' # Adjust port if needed
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
