name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout autoPortfolio repository
        uses: actions/checkout@v4
        with:
          repository: fjuza1/autoPortfolio
          ref: experimental
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Install dependencies in autoPortfolio
      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/autoPortfolio # specify directory if needed

      # Step 3: Start server for autoPortfolio
      - name: Start server
        run: npm start
        working-directory: ${{ github.workspace }}/autoPortfolio # specify directory if needed

      # Step 4: Checkout the Cypress tests repository (portfolioCypress)
      - name: Checkout portfolioCypress repository
        uses: actions/checkout@v4
        with:
          repository: fjuza1/portfolioCypress
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:1234' # Adjust port if needed
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
