name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: windows-latest  # Use windows-latest for Windows environment
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fjuza1/autoPortfolio
          ref: experimental
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: |
          Start-Process "npm" "start" -NoNewWindow
          Start-Sleep -Seconds 10  # Wait for server to be ready (adjust the time if needed)

      - name: Cypress
        uses: actions/checkout@v4
        with:
          repository: fjuza1/portfolioCypress
          ref: main
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:1234'  # Adjust port if needed
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
