name: Cypress Tests
on: [push, pull_request]  # Allow both push and pull request triggers

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'https://splendid-sunburst-2a1df8.netlify.app'  # Waits for Netlify URL
          record: false  # Disable recording to avoid PR data access issues
          parallel: false  # Disable parallelization to simplify setup
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
